#!/usr/bin/env python3
"""Build only upstream native primitives. Generated adaptations fail closed when upstream contracts change."""
from pathlib import Path
import hashlib
import plistlib

root = Path(__file__).resolve().parent.parent
project = root / 'HypnosSpeech.xcodeproj'
project.mkdir(exist_ok=True)
generated = root / '.hypnos-native'
generated.mkdir(exist_ok=True)

def adapt(path, transform):
    text = (root / path).read_text()
    result = transform(text)
    target = generated / Path(path).name
    target.write_text('// Generated by prepare-hypnos-project.py from ' + path + '\n' + result)
    return str(target.relative_to(root))

def replace_once(text, before, after):
    assert text.count(before) == 1, f'Upstream contract changed: {before[:80]}'
    return text.replace(before, after)

def paste_without_local_ai(text):
    start = text.index('        if allowAutoLearn && AutoLearnSettings.isEnabled {')
    end = text.index('        if shouldRestoreClipboard {', start)
    block = text[start:end]
    assert 'pasteDidFinish' in block and 'autoLearnGeneration = nil' in block
    return text[:start] + '        pasteResult = await postPasteCommand()\n        autoLearnGeneration = nil\n' + text[end:]

def shortcut_action(text):
    start = text.index('        case .mode(let id):', text.index('var displayName'))
    end = text.index('        case .recorderPanelEscape:', start)
    return text[:start] + '        case .mode:\n            return String(localized: "Mode")\n' + text[end:]

def shortcut_store(text):
    lines = text.splitlines(keepends=True)
    removed = [line for line in lines if 'ShortcutMigration.removeLegacy' in line]
    assert len(removed) == 6, 'Upstream shortcut migration contract changed'
    return ''.join(line for line in lines if line not in removed)

def recorder_components(text):
    markers = ['// MARK: - Close Button', '// MARK: - Processing Indicator',
               '// MARK: - Progress Dot Animation', '// MARK: - Recorder Status Display']
    parts = []
    for marker in markers:
        start = text.index(marker)
        end = text.index('// MARK:', start + len(marker))
        parts.append(text[start:end])
    return 'import SwiftUI\n' + '\n'.join(parts)

sources = [
    'VoiceInk/Infrastructure/Audio/CoreAudioRecorder.swift',
    'VoiceInk/Infrastructure/Credentials/KeychainService.swift',
    'VoiceInk/Infrastructure/SystemIntegration/Paste/PasteMethod.swift',
    'VoiceInk/Infrastructure/SystemIntegration/Paste/ClipboardManager.swift',
    'VoiceInk/Infrastructure/SystemIntegration/Lifecycle/UserSessionInputPolicy.swift',
    'VoiceInk/Features/Settings/FinishAndSendSettings.swift',
    'VoiceInk/Features/Shortcuts/Models/Shortcut.swift',
    'VoiceInk/Features/Shortcuts/Coordination/ShortcutMonitor.swift',
    'VoiceInk/Features/Recording/Components/AudioVisualizerView.swift',
    'VoiceInk/Features/Recording/Presentation/MiniRecorderPanel.swift',
    'VoiceInk/Features/Recording/Presentation/RecorderScreenResolver.swift',
    'VoiceInk/Core/Recording/RecordingState.swift',
    'VoiceInk/DesignSystem/Theme/AppTheme.swift',
    adapt('VoiceInk/Infrastructure/SystemIntegration/Paste/CursorPaster.swift', paste_without_local_ai),
    adapt('VoiceInk/Features/Shortcuts/Models/ShortcutAction.swift', shortcut_action),
    adapt('VoiceInk/Features/Shortcuts/State/ShortcutStore.swift', shortcut_store),
    adapt('VoiceInk/Features/Shortcuts/State/ShortcutValidator.swift', lambda text: replace_once(text, '            + ModeManager.shared.configurations.map { ShortcutAction.mode($0.id) }', '')),
    adapt('VoiceInk/Features/Shortcuts/Views/ShortcutRecorder.swift', lambda text: replace_once(text, 'NotificationManager.shared.showNotification(', 'HypnosAlert.showNotification(')),
    adapt('VoiceInk/Features/Recording/Components/RecorderComponents.swift', recorder_components),
] + [str(path.relative_to(root)) for path in sorted((root / 'VoiceInk/Hypnos').rglob('*.swift'))]
objects = {}
def oid(name): return hashlib.sha256(name.encode()).hexdigest()[:24].upper()
def obj(object_key, isa, **kwargs):
    identity = oid(object_key); objects[identity] = dict(isa=isa, **kwargs); return identity
source_builds, refs = [], []
for path in sources:
    ref = obj('file:' + path, 'PBXFileReference', lastKnownFileType='sourcecode.swift', path=path, sourceTree='SOURCE_ROOT')
    refs.append(ref)
    source_builds.append(obj('build:' + path, 'PBXBuildFile', fileRef=ref))
assets = obj('assets', 'PBXFileReference', lastKnownFileType='folder.assetcatalog', path='VoiceInk/Assets.xcassets', sourceTree='SOURCE_ROOT')
refs.append(assets)
resource = obj('asset-build', 'PBXBuildFile', fileRef=assets)
product = obj('product', 'PBXFileReference', explicitFileType='wrapper.application', path='Hypnos Speech.app', sourceTree='BUILT_PRODUCTS_DIR')
products = obj('products', 'PBXGroup', children=[product], name='Products', sourceTree='<group>')
group = obj('group', 'PBXGroup', children=refs + [products], sourceTree='<group>')
package = obj('atomics-package', 'XCRemoteSwiftPackageReference', repositoryURL='https://github.com/apple/swift-atomics.git', requirement=dict(kind='exactVersion', version='1.3.0'))
atomics = obj('atomics-product', 'XCSwiftPackageProductDependency', package=package, productName='Atomics')
framework_build = obj('atomics-build', 'PBXBuildFile', productRef=atomics)
source_phase = obj('source-phase', 'PBXSourcesBuildPhase', buildActionMask=2147483647, files=source_builds, runOnlyForDeploymentPostprocessing=0)
resource_phase = obj('resources-phase', 'PBXResourcesBuildPhase', buildActionMask=2147483647, files=[resource], runOnlyForDeploymentPostprocessing=0)
framework_phase = obj('framework-phase', 'PBXFrameworksBuildPhase', buildActionMask=2147483647, files=[framework_build], runOnlyForDeploymentPostprocessing=0)
settings = dict(ALWAYS_SEARCH_USER_PATHS='NO', SDKROOT='macosx', MACOSX_DEPLOYMENT_TARGET='15.0', SWIFT_VERSION='5.0',
                SWIFT_ACTIVE_COMPILATION_CONDITIONS='LOCAL_BUILD HYPNOS_SPEECH',
                PRODUCT_NAME='Hypnos Speech', PRODUCT_MODULE_NAME='HypnosSpeech',
                PRODUCT_BUNDLE_IDENTIFIER='space.hypnos.speech.mac',
                GENERATE_INFOPLIST_FILE='YES', INFOPLIST_FILE='HypnosSpeech/Info.plist',
                INFOPLIST_KEY_CFBundleDisplayName='Hypnos Speech',
                MARKETING_VERSION='0.1.0', CURRENT_PROJECT_VERSION='1',
                ASSETCATALOG_COMPILER_APPICON_NAME='AppIcon', ENABLE_HARDENED_RUNTIME='YES',
                CODE_SIGN_STYLE='Manual', CODE_SIGN_IDENTITY='-',
                CODE_SIGN_ENTITLEMENTS='HypnosSpeech/HypnosSpeech.entitlements',
                LD_RUNPATH_SEARCH_PATHS='$(inherited) @executable_path/../Frameworks')
configs = [obj('target-' + name, 'XCBuildConfiguration', name=name, buildSettings=dict(settings, SWIFT_OPTIMIZATION_LEVEL='-O' if name == 'Release' else '-Onone')) for name in ['Debug', 'Release']]
config_list = obj('target-configs', 'XCConfigurationList', buildConfigurations=configs, defaultConfigurationIsVisible=0, defaultConfigurationName='Release')
target = obj('target', 'PBXNativeTarget', name='Hypnos Speech', productName='Hypnos Speech', productReference=product,
             productType='com.apple.product-type.application', buildConfigurationList=config_list,
             buildPhases=[source_phase, framework_phase, resource_phase], buildRules=[], dependencies=[], packageProductDependencies=[atomics])
project_configs = [obj('project-' + name, 'XCBuildConfiguration', name=name, buildSettings={}) for name in ['Debug', 'Release']]
project_config_list = obj('project-configs', 'XCConfigurationList', buildConfigurations=project_configs, defaultConfigurationIsVisible=0, defaultConfigurationName='Release')
root_obj = obj('project', 'PBXProject', attributes=dict(LastUpgradeCheck='2630'), buildConfigurationList=project_config_list,
               compatibilityVersion='Xcode 15.0', developmentRegion='en', hasScannedForEncodings=0,
               knownRegions=['en', 'Base'], mainGroup=group, productRefGroup=products, projectDirPath='',
               projectRoot='', targets=[target], packageReferences=[package])
(project / 'project.pbxproj').write_bytes(plistlib.dumps(dict(archiveVersion='1', classes={}, objectVersion='56', objects=objects, rootObject=root_obj)))
print(f'Generated capture-only project: {len(sources)} Swift files, Swift Atomics 1.3.0; no inference/updater dependencies.')
